sonar.projectKey=cybersapienseci_identity-service
sonar.organization=cybersapienseci
sonar.projectName=AlphaECI Identity Service

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Fail the pipeline if the Quality Gate does not pass (>80% coverage required via QG)
sonar.qualitygate.wait=false

# Exclude from both analysis and coverage
sonar.exclusions=\
  **/dto/**,\
  **/*Application.java,\
  **/config/**,\
  **/infrastructure/persistence/entity/**

sonar.coverage.exclusions=\
  **/dto/**,\
  **/*Application.java,\
  **/config/**,\
  **/infrastructure/**,\
  **/entrypoints/**

sonar.cpd.exclusions=**/dto/**
