name: CD – Deploy to Prod

on:
  workflow_run:
    workflows: ["CD – Deploy to QA"]
    branches: [main]
    types: [completed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cybersapienseci/identity-service
  RESOURCE_GROUP: alphaECI-prod

jobs:

  deploy-prod:
    name: "Deploy to Prod"
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Prod Container App
        run: |
          az containerapp registry set \
            --name alphaeci-identity-service-prod \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --server ghcr.io \
            --username ${{ github.repository_owner }} \
            --password ${{ secrets.GHCR_TOKEN }}
          az containerapp update \
            --name alphaeci-identity-service-prod \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:qa-${{ github.event.workflow_run.head_sha }}
